name: module3_task0
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
      - uses: actions/checkout@v3

      - name: running make help
      - run: make help -C module3_task0
